### ISSUE TITLE
程序無法啟動

### ISSUE THREAD

**Issue by didiyee87** [TheFunny/ArisuAutoSweeper#2]
═══════════════════════════════════════════════════════════════════════════════
                                     START                                     
═══════════════════════════════════════════════════════════════════════════════
═══════════════════════════════════════════════════════════════════════════════
                                     START                                     
═══════════════════════════════════════════════════════════════════════════════
INFO     2023-11-11 09:22:39.799 │ <<< LAUNCHER CONFIG >>>                     
INFO     2023-11-11 09:22:39.800 │ [Host] 0.0.0.0                              
INFO     2023-11-11 09:22:39.801 │ [Port] 22367                                
INFO     2023-11-11 09:22:39.802 │ [Electron] True                             
INFO     2023-11-11 09:22:39.803 │ [Reload] True                               
INFO     2023-11-11 09:22:39.803 │ Electron detected, remove log output to     
         stdout                                                                
Process Process-1:
Traceback (most recent call last):
  File "D:\ArisuAutoSweeper\toolkit\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "D:\ArisuAutoSweeper\toolkit\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "D:\ArisuAutoSweeper\gui.py", line 67, in func
    uvicorn.run("module.webui.app:app", host=host, port=port, factory=True)
  File "D:\ArisuAutoSweeper\toolkit\lib\site-packages\uvicorn\main.py", line 463, in run
    server.run()
  File "D:\ArisuAutoSweeper\toolkit\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "D:\ArisuAutoSweeper\toolkit\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\ArisuAutoSweeper\toolkit\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "D:\ArisuAutoSweeper\toolkit\lib\site-packages\uvicorn\server.py", line 67, in serve
    config.load()
  File "D:\ArisuAutoSweeper\toolkit\lib\site-packages\uvicorn\config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
  File "D:\ArisuAutoSweeper\toolkit\lib\site-packages\uvicorn\importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "D:\ArisuAutoSweeper\toolkit\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ArisuAutoSweeper\module\webui\app.py", line 49, in <module>
    from module.webui.base import Frame
  File "D:\ArisuAutoSweeper\module\webui\base.py", line 6, in <module>
    from module.webui.utils import Icon, WebIOTaskHandler, set_localstorage
  File "D:\ArisuAutoSweeper\module\webui\utils.py", line 383, in <module>
    class Icon:
  File "D:\ArisuAutoSweeper\module\webui\utils.py", line 388, in Icon
    ALAS = _read(filepath_icon("alas"))
  File "D:\ArisuAutoSweeper\module\webui\utils.py", line 380, in _read
    return f.read()
UnicodeDecodeError: 'cp950' codec can't decode byte 0x90 in position 455: illegal multibyte sequence

![image](https://github.com/TheFunny/ArisuAutoSweeper/assets/57474822/75b38d7e-bb2a-418d-8947-2117de8b993d)

編碼出了點問題?

**Comment by TheFunny** [comment]
已尝试修复于 https://github.com/TheFunny/ArisuAutoSweeper/commit/b0621b48e63e86e9f55e0d85fd9161f60b018df9

请更新并观察问题是否复现

**Comment by didiyee87** [comment]
> 已尝试修复于 [b0621b4](https://github.com/TheFunny/ArisuAutoSweeper/commit/b0621b48e63e86e9f55e0d85fd9161f60b018df9)
> 
> 请更新并观察问题是否复现

已能正常啟動 感謝
